### ISSUE TITLE
Missing custom Open ID Connect Endpoint to Query PlayFab Id

### ISSUE THREAD

**Issue by HelloKitty** [PlayFab/CSharpSDK#106]
I cannot find in the API nor the documentation on where/how to query PlayFab for the PlayFabId connected to a custom Open Id Connect provider. For example, this API endpoint exists for the Xbox: <https://api.playfab.com/documentation/server/method/GetPlayFabIDsFromXboxLiveIDs> but with my custom Open Id Connect service I cannot convert a known account id to a PlayFab Id. Sure, I could add it to a database on creation but most services do not have direct access to this service or database. They just have the client OAuth JWT.

Am I missing something? Is this a feature that I should not be looking for?

**Comment by HelloKitty** [comment]
I have decided the best approach would be to integrate the PlayfabId as a claim on the JWT and deal with it at registration time.

I still think that this lookup should be possible though but this other approach will work too with some effort.

**Comment by pgilmorepf** [comment]
Thank you for your suggestion.
I'll send it to a dev team for consideration.
It's my personal opinion that this request will be regarded as low priority, so I encourage your plans to work around it.
