### ISSUE TITLE
Add ConfigureAwait(false) to PlayFabSysHttp.DoPost

### ISSUE THREAD

**Issue by dmanning23** [PlayFab/CSharpSDK#109]
The following lines of code should be changed to include ConfigureAwait(false):

https://github.com/PlayFab/CSharpSDK/blob/d61ba9f23bf459e6b766bc3fd6b0945ede9ef553/PlayFabSDK/source/PlayFabHttp/PlayFabSysHttp.cs#L52
https://github.com/PlayFab/CSharpSDK/blob/d61ba9f23bf459e6b766bc3fd6b0945ede9ef553/PlayFabSDK/source/PlayFabHttp/PlayFabSysHttp.cs#L53

I ran into an issue when calling a PlayFab method from an event handler where the `PostAsync` call was trying to grab the main UI thread context and deadlocking the app. Since this was in an `async void` event handler, it is not possible to properly await.

I was able to fix this issue by cloning this repo from source and manually adding `ConfigureAwait(false)` all the way down into this method call.

Here is an article with more detail explaining use of ConfigureAwait in library code:
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

Super appreciate the work yall are doing on the PlayFab CSharkSDK.
Cheers!

**Comment by pgilmorepf** [comment]
What are your thoughts about this?
https://blogs.msdn.microsoft.com/benwilli/2017/02/09/an-alternative-to-configureawaitfalse-everywhere/

**Comment by pgilmorepf** [comment]
We have applied a very similar fix, so this issue should be resolved.
Thanks for your suggestion.
